export interface CommitteeMember {
  name: string;           // Short name shown on card banner
  full_name: string;      // Full name in expanded view
  year_course: string;    // e.g. "Y2 / Computer Science"
  og: string;             // e.g. "OG 3"
  first_image: string;    // Front-facing photo path
  second_image: string;   // Alternate / fun photo path
}

export interface CommitteeTopic {
  title: string;                   // Banner title, e.g. "TOPS & MC"
  group_image: string;             // Group photo for the top banner
  members: CommitteeMember[];
}

// ─── Placeholder data — replace with real members ───────────────

const NAMES = [
  "Alice", "Bob", "Charlie", "Diana", "Eve", "Frank", "Grace", "Hank",
  "Iris", "Jack", "Karen", "Leo", "Mia", "Noah", "Olivia", "Pete",
  "Quinn", "Ryan", "Sara", "Tom",
];

const placeholder = (name: string, i: number): CommitteeMember => ({
  name,
  full_name: `${name} Placeholder`,
  year_course: `Y${(i % 4) + 1} / Course`,
  og: `OG ${(i % 8) + 1}`,
  first_image: "/images/finn.png",
  second_image: "/images/jake.png",
});

/** Generate N placeholder members from the names pool */
const generateMembers = (count: number): CommitteeMember[] =>
  Array.from({ length: count }, (_, i) =>
    placeholder(NAMES[i % NAMES.length], i),
  );

export const committeeTopics: CommitteeTopic[] = [
  {
    title: "TOPS n MC",
    group_image: "/images/committee/MC/TOPS/TOPS.jpg",
    members: [
  {
    name: "Sheryn",
    full_name: "Sheryn Wu",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/TOPS/SHERYN1.jpg",
    second_image: "/images/committee/mc/TOPS/SHERYN2.jpg",
  },
  {
    name: "Via",
    full_name: "Agatha Kristanavia",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/tops/VIA1.jpg",
    second_image: "/images/committee/mc/tops/VIA2.jpg",
  },
  {
    name: "Jason",
    full_name: "Jason Lihan",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/tops/JASON1.jpg",
    second_image: "/images/committee/mc/tops/JASON2.jpg",
  },
  {
    name: "Olin",
    full_name: "Caroline Wijaya",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/tops/CAROLINE1.jpg",
    second_image: "/images/committee/mc/tops/CAROLINE2.jpg",
  },
  {
    name: "Sharon",
    full_name: "Gabriella Sharon Gunawan",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/bfm/SHARON1.jpg",
    second_image: "/images/committee/mc/bfm/SHARON2.jpg",
  },
  {
    name: "Janice",
    full_name: "Janice Vashti",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/bfm/JANICE1.jpg",
    second_image: "/images/committee/mc/bfm/JANICE2.jpg",
  },
  {
    name: "Michelle",
    full_name: "Michelle Priscilla Hung",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/bfm/MICHELLE1.jpg",
    second_image: "/images/committee/mc/bfm/MICHELLE2.jpg",
  },
  {
    name: "Judah",
    full_name: "Judah Valiant Primeldi",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/gl/JUDAH1.jpg",
    second_image: "/images/committee/mc/gl/JUDAH2.jpg",
  },
  {
    name: "Naja",
    full_name: "Naja Andria Mumtaz",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/gl/NAJA1.jpg",
    second_image: "/images/committee/mc/gl/NAJA2.jpg",
  },
  {
    name: "Alexander",
    full_name: "Alexander Sutanto Herlington",
    year_course: "",
    og: "",
    first_image: "/images/committee/MC/polog/ALEXANDER1.jpg",
    second_image: "/images/committee/MC/polog/ALEXANDER2.jpg",
  },
  {
    name: "Chloe",
    full_name: "Chloe Atipinati Djohan",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/polog/CHLOE1.jpg",
    second_image: "/images/committee/mc/polog/CHLOE2.jpg",
  },
  {
    name: "Daniel",
    full_name: "Daniel Lee",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/polog/DANIEL1.jpg",
    second_image: "/images/committee/mc/polog/DANIEL2.jpg",
  },
  {
    name: "Gabbie",
    full_name: "Gabbie Clarissa Utama",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/polog/GABBIE1.jpg",
    second_image: "/images/committee/mc/polog/GABBIE2.jpg",
  },
  {
    name: "Kevin",
    full_name: "Kevin Raditya Mahendra",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/polog/KEVIN1.jpg",
    second_image: "/images/committee/mc/polog/KEVIN2.jpg",
  },
  {
    name: "Michael",
    full_name: "Michael Angelo",
    year_course: "",
    og: "",
    first_image: "/images/committee/MC/POLOG/MICHAEL1.jpg",
    second_image: "/images/committee/MC/POLOG/MICHAEL2.jpg",
  },
  {
    name: "Nickholas",
    full_name: "Nickholas Jamie Jorrey",
    year_course: "",
    og: "",
    first_image: "/images/committee/MC/POLOG/NICKHOLAS1.jpg",
    second_image: "/images/committee/MC/POLOG/NICKHOLAS2.jpg",
  },
  {
    name: "Anastasia",
    full_name: "Anastasia Koesoemo",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/ppit/ANASTASIA1.jpg",
    second_image: "/images/committee/mc/ppit/ANASTASIA2.jpg",
  },
  {
    name: "Enzio",
    full_name: "Enzio Dwiputra Sujandi",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/ppit/ENZIO1.jpg",
    second_image: "/images/committee/mc/ppit/ENZIO2.jpg",
  },
  {
    name: "Nada",
    full_name: "Nada Shafiyah R.",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/ppit/NADA1.jpg",
    second_image: "/images/committee/mc/ppit/NADA2.jpg",
  },
  {
    name: "William",
    full_name: "William Mulia",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/ppit/WILLIAM1.jpg",
    second_image: "/images/committee/mc/ppit/WILLIAM2.jpg",
  },
  {
    name: "David",
    full_name: "David Runako",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/welfare/DAVID1.jpg",
    second_image: "/images/committee/mc/welfare/DAVID2.jpg",
  },
  {
    name: "Nisa",
    full_name: "Hayrunnisa Nur Cil",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/welfare/NISA1.jpg",
    second_image: "/images/committee/mc/welfare/NISA2.jpg",
  },
  {
    name: "Ais",
    full_name: "Nabila Rahma Aisyah",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/welfare/AIS1.jpg",
    second_image: "/images/committee/mc/welfare/AIS2.jpg",
  },
  {
    name: "Najwa",
    full_name: "Najwa Nahfisah Putri",
    year_course: "",
    og: "",
    first_image: "/images/committee/mc/welfare/NAJWA1.jpg",
    second_image: "/images/committee/mc/welfare/NAJWA2.jpg",
  },
],
  },
  {
    title: "GL",
    group_image: "/images/committee/GL/GL_MC.jpg",
    members: [
  {
    name: "Mikael",
    full_name: "Mikael Ernest Susanto",
    year_course: "",
    og: "1",
    first_image: "/images/committee/gl/MIKAEL1.jpg",
    second_image: "/images/committee/gl/MIKAEL2.jpg",
  },
  {
    name: "Jenica",
    full_name: "Jenica Avela Setiawan",
    year_course: "",
    og: "1",
    first_image: "/images/committee/gl/JENICA1.jpg",
    second_image: "/images/committee/gl/JENICA2.jpg",
  },
  {
    name: "Kenneth",
    full_name: "Kenneth Joshua",
    year_course: "",
    og: "2",
    first_image: "/images/committee/gl/KENNETH1.jpg",
    second_image: "/images/committee/gl/KENNETH2.jpg",
  },
  {
    name: "Annabelle",
    full_name: "Annabelle Qetsyah Putri Setyawan",
    year_course: "",
    og: "2",
    first_image: "/images/committee/gl/ANNABELLE1.jpg",
    second_image: "/images/committee/gl/ANNABELLE2.jpg",
  },
  {
    name: "Dhammananda",
    full_name: "Dhammanananda Justin Yu",
    year_course: "",
    og: " OG 3",
    first_image: "/images/committee/gl/Dhammananda1.jpg",
    second_image: "/images/committee/gl/Dhammananda2.jpg",
  },
  {
    name: "Farra",
    full_name: "Farra Iva Karjadhi",
    year_course: "",
    og: "3",
    first_image: "/images/committee/gl/FARRA1.jpg",
    second_image: "/images/committee/gl/FARRA2.jpg",
  },
  {
    name: "Jay",
    full_name: "Jay Riva Opi",
    year_course: "",
    og: "4",
    first_image: "/images/committee/gl/JAY1.jpg",
    second_image: "/images/committee/gl/JAY2.jpg",
  },
  {
    name: "Vania",
    full_name: "Vania Jovelyn Nando",
    year_course: "",
    og: "4",
    first_image: "/images/committee/gl/VANIA1.jpg",
    second_image: "/images/committee/gl/VANIA2.jpg",
  },
  {
    name: "Panji",
    full_name: "Panji Ndika Saputra Wijaya",
    year_course: "",
    og: "5",
    first_image: "/images/committee/gl/PANJI1.jpg",
    second_image: "/images/committee/gl/PANJI2.jpg",
  },
  {
    name: "Alkheisya",
    full_name: "Alkheisya Nabila Slavina",
    year_course: "",
    og: "5",
    first_image: "/images/committee/gl/ALKHEISYA1.jpg",
    second_image: "/images/committee/gl/ALKHEISYA2.jpg",
  },
  {
    name: "Azzam",
    full_name: "Azzam Harzuqi",
    year_course: "",
    og: "6",
    first_image: "/images/committee/gl/AZZAM1.jpg",
    second_image: "/images/committee/gl/AZZAM2.jpg",
  },
  {
    name: "Amelia",
    full_name: "Amelia Chantiqa Dewi",
    year_course: "",
    og: "6",
    first_image: "/images/committee/gl/AMELIA1.jpg",
    second_image: "/images/committee/gl/AMELIA2.jpg",
  },
  {
    name: "Marcellino",
    full_name: "Marcellino Grant Hadisiswoyo",
    year_course: "",
    og: "7",
    first_image: "/images/committee/gl/MARCELLINO1.jpg",
    second_image: "/images/committee/gl/MARCELLINO2.jpg",
  },
  {
    name: "Kevina",
    full_name: "Kevina Arin Lucelta",
    year_course: "",
    og: "7",
    first_image: "/images/committee/gl/KEVINA1.jpg",
    second_image: "/images/committee/gl/KEVINA2.jpg",
  },
  {
    name: "Ignatius",
    full_name: "Ignatius Jovan Liem",
    year_course: "",
    og: "8",
    first_image: "/images/committee/gl/IGNATIUS1.jpg",
    second_image: "/images/committee/gl/IGNATIUS2.jpg",
  },
  {
    name: "Olga",
    full_name: "Olga Adelaine Kosasih",
    year_course: "",
    og: "8",
    first_image: "/images/committee/gl/OLGA1.jpg",
    second_image: "/images/committee/gl/OLGA2.jpg",
  },
],
  },
  {
    title: "PPIT",
    group_image: "/images/committee/ppit/PPIT_MC.jpg",
    members: [
  {
    name: "Alisha",
    full_name: "Alisha Clea Candra",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/ALISHA1.jpg",
    second_image: "/images/committee/ppit/ALISHA2.jpg",
  },
  {
    name: "Ariel",
    full_name: "Ariel Willy Saragi S",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/ARIEL1.jpg",
    second_image: "/images/committee/ppit/ARIEL2.jpg",
  },
  {
    name: "Carrie",
    full_name: "Carrie Putri Sanria",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/CARRIE1.jpg",
    second_image: "/images/committee/ppit/CARRIE2.jpg",
  },
  {
    name: "Catharina",
    full_name: "Catharina Calista Samirin",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/CATHARINA1.jpg",
    second_image: "/images/committee/ppit/CATHARINA2.jpg",
  },
  {
    name: "Jovica",
    full_name: "Jovica Marcia Sugianto",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/JOVICA1.jpg",
    second_image: "/images/committee/ppit/JOVICA2.jpg",
  },
  {
    name: "Nathanael",
    full_name: "Nathanael Nicolas Chang",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/NATHANAEL1.jpg",
    second_image: "/images/committee/ppit/NATHANAEL2.jpg",
  },
  {
    name: "Naura",
    full_name: "Naura Reva Aulia",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/NAURA1.jpg",
    second_image: "/images/committee/ppit/NAURA2.jpg",
  },
  {
    name: "Sebastian",
    full_name: "Sebastian Maximillian Martan",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/SEBASTIAN1.jpg",
    second_image: "/images/committee/ppit/SEBASTIAN2.jpg",
  },
  {
    name: "Alexandra",
    full_name: "Alexandra Naomira Krisdianto",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/ALEXANDRA1.jpg",
    second_image: "/images/committee/ppit/ALEXANDRA2.jpg",
  },
  {
    name: "Askana",
    full_name: "Askana Mirza Mawlana Irfany",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/ASKANA1.jpg",
    second_image: "/images/committee/ppit/ASKANA2.jpg",
  },
  {
    name: "Brayden",
    full_name: "Brayden Tanto",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/BRAYDEN1.jpg",
    second_image: "/images/committee/ppit/BRAYDEN2.jpg",
  },
  {
    name: "Justin",
    full_name: "Justin Manggala",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/JUSTIN1.jpg",
    second_image: "/images/committee/ppit/JUSTIN2.jpg",
  },
  {
    name: "Margaret",
    full_name: "Margaret Kaylin Wibisono",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/MARGARET1.jpg",
    second_image: "/images/committee/ppit/MARGARET2.jpg",
  },
  {
    name: "Muhammad",
    full_name: "Muhammad Nabil Hidayat",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/MUHAMMAD1.jpg",
    second_image: "/images/committee/ppit/MUHAMMAD2.jpg",
  },
  {
    name: "Radoslaw",
    full_name: "Radoslaw Aryananda",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/RADOSLAW1.jpg",
    second_image: "/images/committee/ppit/RADOSLAW2.jpg",
  },
  {
    name: "Sayyed",
    full_name: "Sayyed Muhammed Ridzwan Harahap",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/SAYYED1.jpg",
    second_image: "/images/committee/ppit/SAYYED2.jpg",
  },
  {
    name: "Zeus",
    full_name: "Zeus Hyde Kurniawan Poerwanto",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/ZEUS1.jpg",
    second_image: "/images/committee/ppit/ZEUS2.jpg",
  },
  {
    name: "Bernardinus",
    full_name: "Bernardinus Gabriel Hermawan",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/BERNARDINUS1.jpg",
    second_image: "/images/committee/ppit/BERNARDINUS2.jpg",
  },
  {
    name: "Feryan",
    full_name: "Feryan Krishany Jonandri",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/FERYAN1.jpg",
    second_image: "/images/committee/ppit/FERYAN2.jpg",
  },
  {
    name: "Gilbert",
    full_name: "Gilbert Adriel Tantoso",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/GILBERT1.jpg",
    second_image: "/images/committee/ppit/GILBERT2.jpg",
  },
  {
    name: "Juan",
    full_name: "Juan Patrick Hasugian",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/JUAN1.jpg",
    second_image: "/images/committee/ppit/JUAN2.jpg",
  },
  {
    name: "Nadhim",
    full_name: "Nadhim Muzhaffar Hakim",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/NADHIM1.jpg",
    second_image: "/images/committee/ppit/NADHIM2.jpg",
  },
  {
    name: "Rasyidan",
    full_name: "Rasyidan Naja Asardi",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/RASYIDAN1.jpg",
    second_image: "/images/committee/ppit/RASYIDAN2.jpg",
  },
  {
    name: "Reswara",
    full_name: "Reswara Anargya Dzakirullah",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/RESWARA1.jpg",
    second_image: "/images/committee/ppit/RESWARA2.jpg",
  },
  {
    name: "Richard",
    full_name: "Richard Reinhart",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/RICHARD1.jpg",
    second_image: "/images/committee/ppit/RICHARD2.jpg",
  },
  {
    name: "William",
    full_name: "William Notowibowo",
    year_course: "",
    og: "",
    first_image: "/images/committee/ppit/WILLIAM1.jpg",
    second_image: "/images/committee/ppit/WILLIAM2.jpg",
  },
],
  },
  {
    title: "WELFARE",
    group_image: "/images/committee/welfare/WELFARE_MC.jpg",
    members: [
  {
    name: "Alexandra",
    full_name: "Alexandra Marcelia Sariputera",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/ALEXANDRA1.jpg",
    second_image: "/images/committee/welfare/ALEXANDRA2.jpg",
  },
  {
    name: "Gerard",
    full_name: "Gerard Chang",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/GERARD1.jpg",
    second_image: "/images/committee/welfare/GERARD2.jpg",
  },
  {
    name: "Bianca",
    full_name: "Putu Bianca Evangeline Gandhalika",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/PUTU1.jpg",
    second_image: "/images/committee/welfare/PUTU2.jpg",
  },
  {
    name: "Rosyad",
    full_name: "Rosyad Zulfikar Akbari",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/ROSYAD1.jpg",
    second_image: "/images/committee/welfare/ROSYAD2.jpg",
  },
  {
    name: "Ave",
    full_name: "Ni Putu Ary Aveani Sevita Rati",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/I_KADEK1.jpg",
    second_image: "/images/committee/welfare/I_KADEK2.jpg",
  },
  {
    name: "Tiago",
    full_name: "Tung Tiago Masimo",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/TUNG1.jpg",
    second_image: "/images/committee/welfare/TUNG2.jpg",
  },
  {
    name: "Wynette",
    full_name: "Wynette Shalomita Soetanto",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/WYNETTE1.jpg",
    second_image: "/images/committee/welfare/WYNETTE2.jpg",
  },
  {
    name: "Arva",
    full_name: "Arva Mochammad Raditia",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/ARVA1.jpg",
    second_image: "/images/committee/welfare/ARVA2.jpg",
  },
  {
    name: "Laurencia",
    full_name: "Laurencia Angelina Sugiowantono",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/LAURENCIA1.jpg",
    second_image: "/images/committee/welfare/LAURENCIA2.jpg",
  },
  {
    name: "Hafidz",
    full_name: "Hafidz Atthaya Harsono",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/HAFIDZ1.jpg",
    second_image: "/images/committee/welfare/HAFIDZ2.jpg",
  },
  {
    name: "Kristania",
    full_name: "Kristania Liman",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/KRISTANIA1.jpg",
    second_image: "/images/committee/welfare/KRISTANIA2.jpg",
  },
  {
    name: "Michael W",
    full_name: "Michael Widjaja",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/MICHAEL_WIDJAJA1.jpg",
    second_image: "/images/committee/welfare/MICHAEL_WIDJAJA2.jpg",
  },
  {
    name: "Andhika",
    full_name: "I Kadek Andhika Ary Wiguna",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/ANDHIKA1.jpg",
    second_image: "/images/committee/welfare/ANDHIKA2.jpg",
  },
  {
    name: "Navaro",
    full_name: "Navaro Nayottama",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/NAVARO1.jpg",
    second_image: "/images/committee/welfare/NAVARO2.jpg",
  },
  {
    name: "Callista",
    full_name: "Callista Thamrin",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/CALLISTA1.jpg",
    second_image: "/images/committee/welfare/CALLISTA2.jpg",
  },
  {
    name: "Thomas",
    full_name: "Thomas Chrisant Denen",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/THOMAS1.jpg",
    second_image: "/images/committee/welfare/THOMAS2.jpg",
  },
  {
    name: "Rajendra",
    full_name: "Rajendra Maximiliano Dakara",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/RAJENDRA1.jpg",
    second_image: "/images/committee/welfare/RAJENDRA2.jpg",
  },
  {
    name: "Aileen",
    full_name: "Aileen Priskila Permana",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/AILEEN1.jpg",
    second_image: "/images/committee/welfare/AILEEN2.jpg",
  },
  {
    name: "Gabriel",
    full_name: "Gabriel Thane",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/GABRIEL1.jpg",
    second_image: "/images/committee/welfare/GABRIEL2.jpg",
  },
  {
    name: "Alvin",
    full_name: "Shane Alvin S",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/Alvin1.jpg",
    second_image: "/images/committee/welfare/Alvin2.jpg",
  },
  {
    name: "Rachel",
    full_name: "Rachel Finandrie Tjahjadi",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/RACHEL1.jpg",
    second_image: "/images/committee/welfare/RACHEL2.jpg",
  },
  {
    name: "Janice",
    full_name: "Janice Angela Tee",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/JANICE1.jpg",
    second_image: "/images/committee/welfare/JANICE2.jpg",
  },
  {
    name: "Clarissa",
    full_name: "Clarissa Aurelia Glorybel",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/CLARISSA1.jpg",
    second_image: "/images/committee/welfare/CLARISSA2.jpg",
  },
  {
    name: "Albert",
    full_name: "Christopher Albert Tansir",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/ALBERT1.jpg",
    second_image: "/images/committee/welfare/ALBERT2.jpg",
  },
  {
    name: "Gerardo",
    full_name: "Gerardo Nandavardhana Abdipranoto",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/GERARDO1.jpg",
    second_image: "/images/committee/welfare/GERARDO2.jpg",
  },
  {
    name: "Vincent",
    full_name: "Vincent Gilbert Wong",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/VINCENT1.jpg",
    second_image: "/images/committee/welfare/VINCENT2.jpg",
  },
  {
    name: "Michelle",
    full_name: "Michelle Aline Lorenzo",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/MICHELLE1.jpg",
    second_image: "/images/committee/welfare/MICHELLE2.jpg",
  },
  {
    name: "Hans",
    full_name: "Gregory Hans Nugraha",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/HANS1.jpg",
    second_image: "/images/committee/welfare/HANS2.jpg",
  },
  {
    name: "Michael R",
    full_name: "Michael Ryan Sutanto",
    year_course: "",
    og: "",
    first_image: "/images/committee/welfare/MICHAEL_RYAN1.jpg",
    second_image: "/images/committee/welfare/MICHAEL_RYAN2.jpg",
  },
    ],
  },
  {
    title: "POLOG",
    group_image: "/images/finn.png",
    members: generateMembers(20),
  },
  {
    title: "BFM",
    group_image: "/images/committee/bfm/BFM_MC.jpg",
    members: [
  {
    name: "Audria",
    full_name: "Audria Akbar",
    year_course: "",
    og: "",
    first_image: "/images/committee/bfm/audria1.jpg",
    second_image: "/images/committee/bfm/audria2.jpg",
  },
  {
    name: "Christian",
    full_name: "Christian Vilaril Tjendra",
    year_course: "",
    og: "",
    first_image: "/images/committee/bfm/christian1.jpg",
    second_image: "/images/committee/bfm/christian2.jpg",
  },
  {
    name: "Daniel",
    full_name: "Daniel Delin",
    year_course: "",
    og: "",
    first_image: "/images/committee/bfm/daniel1.jpg",
    second_image: "/images/committee/bfm/daniel2.jpg",
  },
  {
    name: "Donni",
    full_name: "Donni Putera Sow",
    year_course: "",
    og: "",
    first_image: "/images/committee/bfm/donni1.jpg",
    second_image: "/images/committee/bfm/donni2.jpg",
  },
  {
    name: "Ivonne",
    full_name: "Ivonne Wijaya",
    year_course: "",
    og: "",
    first_image: "/images/committee/bfm/ivonne1.jpg",
    second_image: "/images/committee/bfm/ivonne2.jpg",
  },
  {
    name: "Keenan",
    full_name: "Keenan Jonathan Maxwell",
    year_course: "",
    og: "",
    first_image: "/images/committee/bfm/keenan1.jpg",
    second_image: "/images/committee/bfm/keenan2.jpg",
  },
  {
    name: "Melly",
    full_name: "Melly Wibowo",
    year_course: "",
    og: "",
    first_image: "/images/committee/bfm/melly1.jpg",
    second_image: "/images/committee/bfm/melly2.jpg",
  },
  {
    name: "Michelle",
    full_name: "Michelle Joandra Hartanto",
    year_course: "",
    og: "",
    first_image: "/images/committee/bfm/michelle1.jpg",
    second_image: "/images/committee/bfm/michelle2.jpg",
  },
  {
    name: "Nicholas",
    full_name: "Nicholas Elbert Liem",
    year_course: "",
    og: "",
    first_image: "/images/committee/bfm/nicholas1.jpg",
    second_image: "/images/committee/bfm/nicholas2.jpg",
  },
  {
    name: "Owen",
    full_name: "Owen Nigel Tjiptarahardja",
    year_course: "",
    og: "",
    first_image: "/images/committee/bfm/owen1.jpg",
    second_image: "/images/committee/bfm/owen2.jpg",
  },
  {
    name: "Stephanie",
    full_name: "Stephanie Nathania Subari",
    year_course: "",
    og: "",
    first_image: "/images/committee/bfm/stephanie1.jpg",
    second_image: "/images/committee/bfm/stephanie2.jpg",
  },
  {
    name: "Vincentius",
    full_name: "Vincentius Farrel Bhaskoro Setyanto",
    year_course: "",
    og: "",
    first_image: "/images/committee/bfm/vicentius1.jpg",
    second_image: "/images/committee/bfm/vicentius2.jpg",
  },
  {
    name: "Viony",
    full_name: "Viony Prajogo",
    year_course: "",
    og: "",
    first_image: "/images/committee/bfm/viony1.jpg",
    second_image: "/images/committee/bfm/viony2.jpg",
  },
],
  },
];