export interface CommitteeMember {
  name: string;           // Short name shown on card banner
  full_name: string;      // Full name in expanded view
  role?: string;          // Committee role, e.g. "President" (TOPS n MC only)
  year_course: string;    // e.g. "Y2 / Computer Science"
  og: string;             // e.g. "OG 3"
  first_image: string;    // Front-facing photo path
  second_image: string;   // Alternate / fun photo path
}

export interface CommitteeTopic {
  title: string;                   // Banner title, e.g. "TOPS & MC"
  group_image: string;             // Group photo for the top banner
  members: CommitteeMember[];
}

// ─── Placeholder data — replace with real members ───────────────

const NAMES = [
  "Alice", "Bob", "Charlie", "Diana", "Eve", "Frank", "Grace", "Hank",
  "Iris", "Jack", "Karen", "Leo", "Mia", "Noah", "Olivia", "Pete",
  "Quinn", "Ryan", "Sara", "Tom",
];

const placeholder = (name: string, i: number): CommitteeMember => ({
  name,
  full_name: `${name} Placeholder`,
  year_course: `Y${(i % 4) + 1} / Course`,
  og: `OG ${(i % 8) + 1}`,
  first_image: "/images/finn.png",
  second_image: "/images/jake.png",
});

/** Generate N placeholder members from the names pool */
const generateMembers = (count: number): CommitteeMember[] =>
  Array.from({ length: count }, (_, i) =>
    placeholder(NAMES[i % NAMES.length], i),
  );

export const committeeTopics: CommitteeTopic[] = [
  {
    title: "TOPS n MC",
    group_image: "/images/committee/MC/TOPS/TOPS.jpg",
    members: [
  {
    name: "Sheryn",
    full_name: "Sheryn Wu",
    role: "President",
    year_course: "MSE/4",
    og: "OG 1",
    first_image: "/images/committee/MC/TOPS/SHERYN1.jpg",
    second_image: "/images/committee/MC/TOPS/SHERYN2.jpg",
  },
  {
    name: "Via",
    full_name: "Agatha Kristanavia",
    role: "TOPS PPIT & BFM",
    year_course: "CBC/4",
    og: "OG 7",
    first_image: "/images/committee/MC/TOPS/VIA1.jpg",
    second_image: "/images/committee/MC/TOPS/VIA2.jpg",
  },
  {
    name: "Jason",
    full_name: "Jason Lihan",
    role: "TOPS GL & WELFARE",
    year_course: "MSE/4",
    og: "OG 6",
    first_image: "/images/committee/MC/TOPS/JASON1.jpg",
    second_image: "/images/committee/MC/TOPS/JASON2.jpg",
  },
  {
    name: "Olin",
    full_name: "Caroline Wijaya Santoso",
    role: "TOPS POLOG",
    year_course: "MSE/4",
    og: "OG 4",
    first_image: "/images/committee/MC/TOPS/CAROLINE1.jpg",
    second_image: "/images/committee/MC/TOPS/CAROLINE2.jpg",
  },
  {
    name: "Sharon",
    full_name: "Gabriella Sharon Gunawan",
    role: "MC BFM",
    year_course: "ME/3",
    og: "OG 2",
    first_image: "/images/committee/MC/BFM/SHARON1.jpg",
    second_image: "/images/committee/MC/BFM/SHARON2.jpg",
  },
  {
    name: "Janice",
    full_name: "Janice Vashti",
    role: "MC BFM",
    year_course: "ECON/4",
    og: "OG 6",
    first_image: "/images/committee/MC/BFM/JANICE1.jpg",
    second_image: "/images/committee/MC/BFM/JANICE2.jpg",
  },
  {
    name: "Michelle",
    full_name: "Michelle Priscilla Hung",
    role: "MC BFM",
    year_course: "CBE/3",
    og: "OG 4",
    first_image: "/images/committee/MC/BFM/MICHELLE1.jpg",
    second_image: "/images/committee/MC/BFM/MICHELLE2.jpg",
  },
  {
    name: "Judah",
    full_name: "Judah Valiant Primeldi",
    role: "CGL",
    year_course: "CBE/3",
    og: "OG 3",
    first_image: "/images/committee/MC/GL/JUDAH1.jpg",
    second_image: "/images/committee/MC/GL/JUDAH2.jpg",
  },
  {
    name: "Naja",
    full_name: "Naja Andria Mumtaz",
    role: "CGL",
    year_course: "BIE/3",
    og: "OG 7",
    first_image: "/images/committee/MC/GL/NAJA1.jpg",
    second_image: "/images/committee/MC/GL/NAJA2.jpg",
  },
  {
    name: "Alex",
    full_name: "Alexander Sutanto Herlington",
    role: "MC POLOG",
    year_course: "CEE/3",
    og: "OG 3",
    first_image: "/images/committee/MC/POLOG/ALEXANDER1.jpg",
    second_image: "/images/committee/MC/POLOG/ALEXANDER2.jpg",
  },
  {
    name: "Chloe",
    full_name: "Chloe Atipinati Djohan",
    role: "MC POLOG",
    year_course: "CSC/3",
    og: "OG 2",
    first_image: "/images/committee/MC/POLOG/CHLOE1.jpg",
    second_image: "/images/committee/MC/POLOG/CHLOE2.jpg",
  },
  {
    name: "Daniel",
    full_name: "Daniel Lee",
    role: "MC POLOG",
    year_course: "EEE/3",
    og: "OG 5",
    first_image: "/images/committee/MC/POLOG/DANIEL1.jpg",
    second_image: "/images/committee/MC/POLOG/DANIEL2.jpg",
  },
  {
    name: "Gabbie",
    full_name: "Gabbie Clarissa Utama",
    role: "MC POLOG",
    year_course: "EEE/3",
    og: "OG 6",
    first_image: "/images/committee/MC/POLOG/GABBIE1.jpg",
    second_image: "/images/committee/MC/POLOG/GABBIE2.jpg",
  },
  {
    name: "Kevin",
    full_name: "Kevin Raditya Mahendra",
    role: "MC POLOG",
    year_course: "MADA/3",
    og: "OG 8",
    first_image: "/images/committee/MC/POLOG/KEVIN1.jpg",
    second_image: "/images/committee/MC/POLOG/KEVIN2.jpg",
  },
  {
    name: "Michael",
    full_name: "Michael Angelo",
    role: "MC POLOG",
    year_course: "ME/3",
    og: "OG 7",
    first_image: "/images/committee/MC/POLOG/MICHAEL1.jpg",
    second_image: "/images/committee/MC/POLOG/MICHAEL2.jpg",
  },
  {
    name: "Nickholas",
    full_name: "Nickholas Jamie Jorrey Pandia",
    role: "MC POLOG",
    year_course: "CEE/3",
    og: "OG 1",
    first_image: "/images/committee/MC/POLOG/NICKHOLAS1.jpg",
    second_image: "/images/committee/MC/POLOG/NICKHOLAS2.jpg",
  },
  {
    name: "Anastasia",
    full_name: "Anastasia Koesoemo",
    role: "MC PPIT",
    year_course: "MADA/3",
    og: "OG 4",
    first_image: "/images/committee/MC/PPIT/ANASTASIA1.jpg",
    second_image: "/images/committee/MC/PPIT/ANASTASIA2.jpg",
  },
  {
    name: "Enzio",
    full_name: "Enzio Dwiputra Sujandi",
    role: "MC PPIT",
    year_course: "CSC/3",
    og: "OG 5",
    first_image: "/images/committee/MC/PPIT/ENZIO1.jpg",
    second_image: "/images/committee/MC/PPIT/ENZIO2.jpg",
  },
  {
    name: "Nada",
    full_name: "Nada Shafiyah Rahmatunnisa",
    role: "MC PPIT",
    year_course: "MSE/3",
    og: "OG 8",
    first_image: "/images/committee/MC/PPIT/NADA1.jpg",
    second_image: "/images/committee/MC/PPIT/NADA2.jpg",
  },
  {
    name: "William",
    full_name: "William Mulia",
    role: "MC PPIT",
    year_course: "CEE/3",
    og: "OG 1",
    first_image: "/images/committee/MC/PPIT/WILLIAM1.jpg",
    second_image: "/images/committee/MC/PPIT/WILLIAM2.jpg",
  },
  {
    name: "David",
    full_name: "David Runako",
    role: "MC WELFARE",
    year_course: "CBE/3",
    og: "OG 2",
    first_image: "/images/committee/MC/WELFARE/DAVID1.jpg",
    second_image: "/images/committee/MC/WELFARE/DAVID2.jpg",
  },
  {
    name: "Nisa",
    full_name: "Hayrunnisa Nur Cil",
    role: "MC WELFARE",
    year_course: "BIE/3",
    og: "OG 5",
    first_image: "/images/committee/MC/WELFARE/NISA1.jpg",
    second_image: "/images/committee/MC/WELFARE/NISA2.jpg",
  },
  {
    name: "Ais",
    full_name: "Nabila Rahma Aisyah",
    role: "MC WELFARE",
    year_course: "CBC/3",
    og: "OG 3",
    first_image: "/images/committee/MC/WELFARE/AIS1.jpg",
    second_image: "/images/committee/MC/WELFARE/AIS2.jpg",
  },
  {
    name: "Najwa",
    full_name: "Najwa Nahfisah Putri",
    role: "MC WELFARE",
    year_course: "ECON/4",
    og: "OG 8",
    first_image: "/images/committee/MC/WELFARE/NAJWA1.jpg",
    second_image: "/images/committee/MC/WELFARE/NAJWA2.jpg",
  },
],
  },
  {
    title: "GL",
    group_image: "/images/committee/gl/GL_MC.jpg",
    members: [
  {
    name: "Mikael",
    full_name: "Mikael Ernest Susanto",
    year_course: "CSC/2",
    og: "OG 1",
    first_image: "/images/committee/gl/MIKAEL1.jpg",
    second_image: "/images/committee/gl/MIKAEL2.jpg",
  },
  {
    name: "Jenica",
    full_name: "Jenica Avela Setiawan",
    year_course: "EEE/2",
    og: "OG 1",
    first_image: "/images/committee/gl/jenica1.jpg",
    second_image: "/images/committee/gl/jenica2.jpg",
  },
  {
    name: "Kenneth",
    full_name: "Kenneth Joshua",
    year_course: "EEE/2",
    og: "OG 2",
    first_image: "/images/committee/gl/KENNETH1.jpg",
    second_image: "/images/committee/gl/KENNETH2.jpg",
  },
  {
    name: "Annabelle",
    full_name: "Annabelle Qetsyah Putri Setyawan",
    year_course: "MSE/2",
    og: "OG 2",
    first_image: "/images/committee/gl/ANNABELLE1.jpg",
    second_image: "/images/committee/gl/ANNABELLE2.jpg",
  },
  {
    name: "Nanda",
    full_name: "Dhammanananda Justin Yu",
    year_course: "BSB/2",
    og: " OG 3",
    first_image: "/images/committee/gl/DHAMMANANDA1.jpg",
    second_image: "/images/committee/gl/DHAMMANANDA2.jpg",
  },
  {
    name: "Farra",
    full_name: "Farra Iva Karjadhi",
    year_course: "BUS/2",
    og: "OG 3",
    first_image: "/images/committee/gl/farra1.jpg",
    second_image: "/images/committee/gl/farra2.jpg",
  },
  {
    name: "Jay",
    full_name: "Jay Riva Opi",
    year_course: "EEE/2",
    og: "OG 4",
    first_image: "/images/committee/gl/jay1.jpg",
    second_image: "/images/committee/gl/jay2.jpg",
  },
  {
    name: "Vania",
    full_name: "Vania Jovelyn Nando",
    year_course: "ME/2",
    og: "OG 4",
    first_image: "/images/committee/gl/VANIA1.jpg",
    second_image: "/images/committee/gl/VANIA2.jpg",
  },
  {
    name: "Panji",
    full_name: "Panji Andika Saputra Wijaya",
    year_course: "ACC/2",
    og: "OG 5",
    first_image: "/images/committee/gl/panji1.jpg",
    second_image: "/images/committee/gl/panji2.jpg",
  },
  {
    name: "Alkheisya",
    full_name: "Alkheisya Nabila Slavina",
    year_course: "SBS/2",
    og: "OG 5",
    first_image: "/images/committee/gl/ALKHEISYA1.jpg",
    second_image: "/images/committee/gl/ALKHEISYA2.jpg",
  },
  {
    name: "Azzam",
    full_name: "Azzam Harzuqi",
    year_course: "CSC/2",
    og: "OG 6",
    first_image: "/images/committee/gl/azzam1.jpg",
    second_image: "/images/committee/gl/azzam2.jpg",
  },
  {
    name: "Amelia",
    full_name: "Amelia Chantiqa Dewi",
    year_course: "BIE/2",
    og: "OG 6",
    first_image: "/images/committee/gl/AMELIA1.jpg",
    second_image: "/images/committee/gl/AMELIA2.jpg",
  },
  {
    name: "Grant",
    full_name: "Marcellino Grant Hadisiswoyo",
    year_course: "EEE/2",
    og: "OG 7",
    first_image: "/images/committee/gl/MARCELLINO1.jpg",
    second_image: "/images/committee/gl/MARCELLINO2.jpg",
  },
  {
    name: "Kevina",
    full_name: "Kevina Arin Lucetta",
    year_course: "DSAI/2",
    og: "OG 7",
    first_image: "/images/committee/gl/KEVINA1.jpg",
    second_image: "/images/committee/gl/KEVINA2.jpg",
  },
  {
    name: "Jovan",
    full_name: "Ignatius Jovan Liem",
    year_course: "DSAI/2",
    og: "OG 8",
    first_image: "/images/committee/gl/IGNATIUS1.jpg",
    second_image: "/images/committee/gl/IGNATIUS2.jpg",
  },
  {
    name: "Olga",
    full_name: "Olga Adelaine Kosasih",
    year_course: "CBE/2",
    og: "OG 8",
    first_image: "/images/committee/gl/olga1.jpg",
    second_image: "/images/committee/gl/olga2.jpg",
  },
],
  },
  {
    title: "PPIT",
    group_image: "/images/committee/ppit/PPIT_MC.jpg",
    members: [
  {
    name: "Alisha",
    full_name: "Alisha Clea Candra",
    year_course: "ADM/2",
    og: "OG 3",
    first_image: "/images/committee/ppit/ALISHA1.jpg",
    second_image: "/images/committee/ppit/ALISHA2.jpg",
  },
  {
    name: "Ariel",
    full_name: "Ariel Willy Saragi S",
    year_course: "ADM/3",
    og: "OG 1",
    first_image: "/images/committee/ppit/ARIEL1.jpg",
    second_image: "/images/committee/ppit/ARIEL2.jpg",
  },
  {
    name: "Aska",
    full_name: "Askana Mirza Mawlana Irfany",
    year_course: "ME/4",
    og: "OG 3",
    first_image: "/images/committee/ppit/ASKANA1.jpg",
    second_image: "/images/committee/ppit/ASKANA2.jpg",
  },
  {
    name: "Awan",
    full_name: "Sayyed Muhammed Ridzwan Harahap",
    year_course: "NBS/3",
    og: "OG 5",
    first_image: "/images/committee/ppit/SAYYED1.jpg",
    second_image: "/images/committee/ppit/SAYYED2.jpg",
  },
  {
    name: "Bernardinus",
    full_name: "Bernardinus Gabriel Hermawan",
    year_course: "IEM/2",
    og: "OG 2",
    first_image: "/images/committee/ppit/BERNARDINUS1.jpg",
    second_image: "/images/committee/ppit/BERNARDINUS2.jpg",
  },
  {
    name: "Brayden",
    full_name: "Brayden Tanto",
    year_course: "EEE/2",
    og: "OG 7",
    first_image: "/images/committee/ppit/BRAYDEN1.jpg",
    second_image: "/images/committee/ppit/BRAYDEN2.jpg",
  },
  {
    name: "Carrie",
    full_name: "Carrie Putri Sanria",
    year_course: "CBE/2",
    og: "OG 3",
    first_image: "/images/committee/ppit/CARRIE1.jpg",
    second_image: "/images/committee/ppit/CARRIE2.jpg",
  },
  {
    name: "Catharina",
    full_name: "Catharina Calista Samirin",
    year_course: "BS/2",
    og: "OG 8",
    first_image: "/images/committee/ppit/CATHARINA1.jpg",
    second_image: "/images/committee/ppit/CATHARINA2.jpg",
  },
  {
    name: "Feryan",
    full_name: "Feryan Krishany Jonandri",
    year_course: "CSC/2",
    og: "OG 6",
    first_image: "/images/committee/ppit/feryan1.jpg",
    second_image: "/images/committee/ppit/feryan2.jpg",
  },
  {
    name: "Gilbert",
    full_name: "Gilbert Adriel Tantoso",
    year_course: "CSC/4",
    og: "OG 5",
    first_image: "/images/committee/ppit/GILBERT1.jpg",
    second_image: "/images/committee/ppit/GILBERT2.jpg",
  },
  {
    name: "Jovica",
    full_name: "Jovica Marcia Sugianto",
    year_course: "IEM/2",
    og: "OG 8",
    first_image: "/images/committee/ppit/JOVICA1.jpg",
    second_image: "/images/committee/ppit/JOVICA2.jpg",
  },
  {
    name: "Juan",
    full_name: "Juan Patrick Hasugian",
    year_course: "EEE/3",
    og: "OG 7",
    first_image: "/images/committee/ppit/JUAN1.jpg",
    second_image: "/images/committee/ppit/JUAN2.jpg",
  },
  {
    name: "Justin",
    full_name: "Justin Manggala",
    year_course: "EEE/2",
    og: "OG 8",
    first_image: "/images/committee/ppit/JUSTIN1.jpg",
    second_image: "/images/committee/ppit/JUSTIN2.jpg",
  },
  {
    name: "Kaylin",
    full_name: "Margaret Kaylin Wibisono",
    year_course: "CBC/2",
    og: "OG 2",
    first_image: "/images/committee/ppit/MARGARET1.jpg",
    second_image: "/images/committee/ppit/MARGARET2.jpg",
  },
  {
    name: "Max",
    full_name: "Sebastian Maximillian Martan",
    year_course: "CBE/3",
    og: "OG 4",
    first_image: "/images/committee/ppit/SEBASTIAN1.jpg",
    second_image: "/images/committee/ppit/SEBASTIAN2.jpg",
  },
  {
    name: "Nabil",
    full_name: "Muhammad Nabil Hidayat",
    year_course: "ME/2",
    og: "OG 3",
    first_image: "/images/committee/ppit/MUHAMMAD1.jpg",
    second_image: "/images/committee/ppit/MUHAMMAD2.jpg",
  },
  {
    name: "Nadhim",
    full_name: "Nadhim Muzhaffar Hakim",
    year_course: "DSAI/2",
    og: "OG 6",
    first_image: "/images/committee/ppit/NADHIM1.jpg",
    second_image: "/images/committee/ppit/NADHIM2.jpg",
  },
  {
    name: "Naomi",
    full_name: "Alexandra Naomira Krisdianto",
    year_course: "EEE/3",
    og: "OG 1",
    first_image: "/images/committee/ppit/ALEXANDRA1.jpg",
    second_image: "/images/committee/ppit/ALEXANDRA2.jpg",
  },
  {
    name: "Nathanael",
    full_name: "Nathanael Nicolas Chang",
    year_course: "CSC/2",
    og: "OG 5",
    first_image: "/images/committee/ppit/NATHANAEL1.jpg",
    second_image: "/images/committee/ppit/NATHANAEL2.jpg",
  },
  {
    name: "Naura",
    full_name: "Naura Reva Aulia",
    year_course: "ADM/3",
    og: "OG 2",
    first_image: "/images/committee/ppit/NAURA1.jpg",
    second_image: "/images/committee/ppit/NAURA2.jpg",
  },
  {
    name: "Radoslaw",
    full_name: "Radoslaw Aryananda",
    year_course: "AISC/2",
    og: "OG 4",
    first_image: "/images/committee/ppit/RADOSLAW1.jpg",
    second_image: "/images/committee/ppit/RADOSLAW2.jpg",
  },
  {
    name: "Resa",
    full_name: "Reswara Anargya Dzakirullah",
    year_course: "CSC/4",
    og: "OG 4",
    first_image: "/images/committee/ppit/RESWARA1.jpg",
    second_image: "/images/committee/ppit/RESWARA2.jpg",
  },
  {
    name: "Richard",
    full_name: "Richard Reinhart",
    year_course: "CSC/2",
    og: "OG 2",
    first_image: "/images/committee/ppit/RICHARD1.jpg",
    second_image: "/images/committee/ppit/RICHARD2.jpg",
  },
  {
    name: "Syidan",
    full_name: "Rasyidan Naja Asardi",
    year_course: "EEE/4",
    og: "OG 1",
    first_image: "/images/committee/ppit/RASYIDAN1.jpg",
    second_image: "/images/committee/ppit/RASYIDAN2.jpg",
  },
  {
    name: "William",
    full_name: "William Notowibowo",
    year_course: "CSC/3",
    og: "OG 7",
    first_image: "/images/committee/ppit/WILLIAM1.jpg",
    second_image: "/images/committee/ppit/WILLIAM2.jpg",
  },
  {
    name: "Zeus",
    full_name: "Zeus Hyde Kurniawan Poerwanto",
    year_course: "ADM/2",
    og: "OG 6",
    first_image: "/images/committee/ppit/zeus1.jpg",
    second_image: "/images/committee/ppit/zeus2.jpg",
  },
],
  },
  {
    title: "WELFARE",
    group_image: "/images/committee/welfare/WELFARE_MC.jpg",
    members: [
  {
    name: "Aileen",
    full_name: "Aileen Priskila Permana",
    year_course: "DSAI/3",
    og: "OG 7",
    first_image: "/images/committee/welfare/AILEEN1.jpg",
    second_image: "/images/committee/welfare/AILEEN2.jpg",
  },
  {
    name: "Albert",
    full_name: "Christopher Albert Tansir",
    year_course: "MSE/2",
    og: "OG 8",
    first_image: "/images/committee/welfare/ALBERT1.jpg",
    second_image: "/images/committee/welfare/ALBERT2.jpg",
  },
  {
    name: "Alexandra",
    full_name: "Alexandra Marcelia",
    year_course: "ECDS/2",
    og: "OG 1",
    first_image: "/images/committee/welfare/ALEXANDRA1.jpg",
    second_image: "/images/committee/welfare/ALEXANDRA2.jpg",
  },
  {
    name: "Alvin",
    full_name: "Shane Alvin",
    year_course: "EESS/2",
    og: "OG 1",
    first_image: "/images/committee/welfare/ALVIN1.jpg",
    second_image: "/images/committee/welfare/ALVIN2.jpg",
  },
  {
    name: "Andhika",
    full_name: "I Kadek Andhika Ary Wiguna",
    year_course: "CBE/2",
    og: "OG 8",
    first_image: "/images/committee/welfare/ANDHIKA1.jpg",
    second_image: "/images/committee/welfare/ANDHIKA2.jpg",
  },
  {
    name: "Arva",
    full_name: "Arva Mochammad Raditia",
    year_course: "MSE/2",
    og: "OG 7",
    first_image: "/images/committee/welfare/ARVA1.jpg",
    second_image: "/images/committee/welfare/ARVA2.jpg",
  },
  {
    name: "Ave",
    full_name: "Ni Putu Ary Aveani Sevita Rati",
    year_course: "BSMCP/2",
    og: "OG 4",
    first_image: "/images/committee/welfare/NI_PUTU1.jpg",
    second_image: "/images/committee/welfare/NI_PUTU2.jpg",
  },
  {
    name: "Bianca",
    full_name: "Putu Bianca Evangeline Gandhalika",
    year_course: "MATH/2",
    og: "OG 5",
    first_image: "/images/committee/welfare/PUTU1.jpg",
    second_image: "/images/committee/welfare/PUTU2.jpg",
  },
  {
    name: "Callista",
    full_name: "Callista Thamrin",
    year_course: "MADA/2",
    og: "OG 2",
    first_image: "/images/committee/welfare/CALLISTA1.jpg",
    second_image: "/images/committee/welfare/CALLISTA2.jpg",
  },
  {
    name: "Clarissa",
    full_name: "Clarissa Aurelia Glorybel",
    year_course: "DSAI/3",
    og: "OG 6",
    first_image: "/images/committee/welfare/CLARISSA1.jpg",
    second_image: "/images/committee/welfare/CLARISSA2.jpg",
  },
  {
    name: "Jonathan",
    full_name: "Jonathan Alfonso Tarman",
    year_course: "ROB/2",
    og: "OG 3",
    first_image: "/images/committee/welfare/JONATHAN1.JPG",
    second_image: "/images/committee/welfare/JONATHAN2.JPG",
  },
  {
    name: "Gabriel",
    full_name: "Gabriel Thane",
    year_course: "MSE/2",
    og: "OG 7",
    first_image: "/images/committee/welfare/GABRIEL1.jpg",
    second_image: "/images/committee/welfare/GABRIEL2.jpg",
  },
  {
    name: "Gerard",
    full_name: "Gerard Chang",
    year_course: "PHY/2",
    og: "OG 4",
    first_image: "/images/committee/welfare/GERARD1.jpg",
    second_image: "/images/committee/welfare/GERARD2.jpg",
  },
  {
    name: "Gerardo",
    full_name: "Gerardo Nandavardhana Abdipranoto",
    year_course: "ME/2",
    og: "OG 4",
    first_image: "/images/committee/welfare/GERARDO1.jpg",
    second_image: "/images/committee/welfare/GERARDO2.jpg",
  },
  {
    name: "Hafidz",
    full_name: "Hafidz Atthaya Harsono",
    year_course: "EEE/2",
    og: "OG 6",
    first_image: "/images/committee/welfare/HAFIDZ1.jpg",
    second_image: "/images/committee/welfare/HAFIDZ2.jpg",
  },
  {
    name: "Hans",
    full_name: "Gregory Hans Nugraha",
    year_course: "ROB/2",
    og: "OG 3",
    first_image: "/images/committee/welfare/HANS1.jpg",
    second_image: "/images/committee/welfare/HANS2.jpg",
  },
  {
    name: "Janice",
    full_name: "Janice Angela Tee",
    year_course: "IEM/4",
    og: "OG 8",
    first_image: "/images/committee/welfare/JANICE1.jpg",
    second_image: "/images/committee/welfare/JANICE2.jpg",
  },
  {
    name: "Kristania",
    full_name: "Kristania Liman",
    year_course: "BIE/2",
    og: "OG 6",
    first_image: "/images/committee/welfare/KRISTANIA1.jpg",
    second_image: "/images/committee/welfare/KRISTANIA2.jpg",
  },
  {
    name: "Laurencia",
    full_name: "Laurencia Angelina",
    year_course: "CBE/3",
    og: "OG 3",
    first_image: "/images/committee/welfare/LAURENCIA1.jpg",
    second_image: "/images/committee/welfare/LAURENCIA2.jpg",
  },
  {
    name: "Michael R",
    full_name: "Michael Ryan Sutanto",
    year_course: "DSAI/2",
    og: "OG 6",
    first_image: "/images/committee/welfare/MICHAEL_RYAN1.jpg",
    second_image: "/images/committee/welfare/MICHAEL_RYAN2.jpg",
  },
  {
    name: "Michael W",
    full_name: "Michael Widjaja",
    year_course: "ROB/2",
    og: "OG 2",
    first_image: "/images/committee/welfare/MICHAEL_WIDJAJA1.jpg",
    second_image: "/images/committee/welfare/MICHAEL_WIDJAJA2.jpg",
  },
  {
    name: "Michelle",
    full_name: "Michelle Aline Lorenzo",
    year_course: "IEM/2",
    og: "OG 7",
    first_image: "/images/committee/welfare/MICHELLE1.jpg",
    second_image: "/images/committee/welfare/MICHELLE2.jpg",
  },
  {
    name: "Rachel",
    full_name: "Rachel Finandrie",
    year_course: "ENE/2",
    og: "OG 1",
    first_image: "/images/committee/welfare/RACHEL1.jpg",
    second_image: "/images/committee/welfare/RACHEL2.jpg",
  },
  {
    name: "Rajendra",
    full_name: "Rajendra Dakara",
    year_course: "CBE/2",
    og: "OG 3",
    first_image: "/images/committee/welfare/RAJENDRA1.jpg",
    second_image: "/images/committee/welfare/RAJENDRA2.jpg",
  },
  {
    name: "Rosyad",
    full_name: "Rosyad Akbari",
    year_course: "CEE/4",
    og: "OG 2",
    first_image: "/images/committee/welfare/ROSYAD1.jpg",
    second_image: "/images/committee/welfare/ROSYAD2.jpg",
  },
  {
    name: "Tama",
    full_name: "Navaro Nayottama",
    year_course: "MSE/2",
    og: "OG 8",
    first_image: "/images/committee/welfare/NAVARO1.jpg",
    second_image: "/images/committee/welfare/NAVARO2.jpg",
  },
  {
    name: "Thomas",
    full_name: "Thomas Chrisant Denen",
    year_course: "ENE/3",
    og: "OG 5",
    first_image: "/images/committee/welfare/THOMAS1.jpg",
    second_image: "/images/committee/welfare/THOMAS2.jpg",
  },
  {
    name: "Tiago",
    full_name: "Tung Tiago Masimo",
    year_course: "BUS/3",
    og: "OG 1",
    first_image: "/images/committee/welfare/TUNG1.jpg",
    second_image: "/images/committee/welfare/TUNG2.jpg",
  },
  {
    name: "Vincent",
    full_name: "Vincent Gilbert Wong",
    year_course: "ME/3",
    og: "OG 5",
    first_image: "/images/committee/welfare/VINCENT1.jpg",
    second_image: "/images/committee/welfare/VINCENT2.jpg",
  },
  {
    name: "Wynette",
    full_name: "Wynette Shalomita Soetanto",
    year_course: "MSE/2",
    og: "OG 4",
    first_image: "/images/committee/welfare/WYNETTE1.jpg",
    second_image: "/images/committee/welfare/WYNETTE2.jpg",
  },
],
  },
  {
    title: "POLOG",
    group_image: "/images/committee/MC/POLOG/POLOG_MC.jpg",
    members: [
  {
    name: "Aaron",
    full_name: "Aaron Evander Kurniawan",
    year_course: "ENE/2",
    og: "OG 1",
    first_image: "/images/committee/polog/AARON1.jpeg",
    second_image: "/images/committee/polog/AARON2.jpeg",
  },
  {
    name: "Archie",
    full_name: "Archie Kenichi Prayogo",
    year_course: "MSE/2",
    og: "OG 4",
    first_image: "/images/committee/polog/ARCHIE1.jpeg",
    second_image: "/images/committee/polog/ARCHIE2.jpeg",
  },
  {
    name: "Bryan",
    full_name: "Bryan Winsley Louwren",
    year_course: "EEE/2",
    og: "OG 3",
    first_image: "/images/committee/polog/BRYAN1.jpeg",
    second_image: "/images/committee/polog/BRYAN2.jpeg",
  },
  {
    name: "Casey",
    full_name: "Casey Bodhiyano",
    year_course: "MACS/2",
    og: "OG 4",
    first_image: "/images/committee/polog/CASEY1.jpeg",
    second_image: "/images/committee/polog/CASEY1.jpeg",
  },
  {
    name: "Celine",
    full_name: "Celine Ruslim",
    year_course: "ME/3",
    og: "OG 7",
    first_image: "/images/committee/polog/CELINE1.jpeg",
    second_image: "/images/committee/polog/CELINE2.jpeg",
  },
  {
    name: "Charles",
    full_name: "Charles Lukas",
    year_course: "EEE/2",
    og: "OG 2",
    first_image: "/images/committee/polog/CHARLES1.jpeg",
    second_image: "/images/committee/polog/CHARLES2.jpeg",
  },
  {
    name: "Cliff",
    full_name: "Cliff Sia",
    year_course: "EEE/4",
    og: "OG 2",
    first_image: "/images/committee/polog/CLIFF1.jpeg",
    second_image: "/images/committee/polog/CLIFF2.jpeg",
  },
  {
    name: "Evan",
    full_name: "Evan Wijaya",
    year_course: "EEE/2",
    og: "OG 5",
    first_image: "/images/committee/polog/EVAN1.jpeg",
    second_image: "/images/committee/polog/EVAN2.jpeg",
  },
  {
    name: "Evelyn",
    full_name: "Evelyn Aurelia Chen",
    year_course: "ADM/2",
    og: "OG 6",
    first_image: "/images/committee/polog/EVELYN1.jpeg",
    second_image: "/images/committee/polog/EVELYN2.jpeg",
  },
  {
    name: "Exel",
    full_name: "Exel Limse",
    year_course: "EEE/3",
    og: "OG 8",
    first_image: "/images/committee/polog/EXEL1.jpeg",
    second_image: "/images/committee/polog/EXEL2.jpeg",
  },
  {
    name: "Felix",
    full_name: "Dominicus Joe Felix",
    year_course: "EEE/2",
    og: "OG 5",
    first_image: "/images/committee/polog/FELIX1.jpeg",
    second_image: "/images/committee/polog/FELIX2.jpeg",
  },
  {
    name: "Filbert",
    full_name: "Filbert Winston",
    year_course: "MSE/2",
    og: "OG 6",
    first_image: "/images/committee/polog/FILBERT1.jpeg",
    second_image: "/images/committee/polog/FILBERT2.jpeg",
  },
  {
    name: "Geraldo",
    full_name: "Geraldo Owen Limantara",
    year_course: "MSE/4",
    og: "OG 7",
    first_image: "/images/committee/polog/GERALDO1.jpeg",
    second_image: "/images/committee/polog/GERALDO2.jpeg",
  },
  {
    name: "Ghaliza",
    full_name: "Ghaliza Pratiwi",
    year_course: "CEE/2",
    og: "OG 7",
    first_image: "/images/committee/polog/GHALIZA1.jpeg",
    second_image: "/images/committee/polog/GHALIZA2.jpeg",
  },
  {
    name: "Haidar",
    full_name: "Haidar Prayata",
    year_course: "MATH/4",
    og: "OG 1",
    first_image: "/images/committee/polog/HAIDAR1.jpeg",
    second_image: "/images/committee/polog/HAIDAR1.jpeg",
  },
  {
    name: "Hansen",
    full_name: "Frederrico Hansen Budianto",
    year_course: "DSAI/4",
    og: "OG 3",
    first_image: "/images/committee/polog/HANSEN1.jpeg",
    second_image: "/images/committee/polog/HANSEN2.jpeg",
  },
  {
    name: "Herbie",
    full_name: "Herbie Tio",
    year_course: "CBE/3",
    og: "OG 4",
    first_image: "/images/committee/polog/HERBIE1.jpeg",
    second_image: "/images/committee/polog/HERBIE2.jpeg",
  },
  {
    name: "Izza",
    full_name: "Nahidh Izzati Silmi",
    year_course: "BIE/2",
    og: "OG 3",
    first_image: "/images/committee/polog/IZZA1.jpeg",
    second_image: "/images/committee/polog/IZZA2.jpeg",
  },
  {
    name: "James K",
    full_name: "James Kenrick",
    year_course: "BSB/3",
    og: "OG 2",
    first_image: "/images/committee/polog/JAMES1.jpg",
    second_image: "/images/committee/polog/JAMES2.jpg",
  },
  {
    name: "James M",
    full_name: "James Matthew Muljono",
    year_course: "MSE/2",
    og: "OG 7",
    first_image: "/images/committee/polog/JAMES_M1.jpeg",
    second_image: "/images/committee/polog/JAMES_M2.jpeg",
  },
  {
    name: "Jericho",
    full_name: "Jericho Liantono",
    year_course: "CE/2",
    og: "OG 8",
    first_image: "/images/committee/polog/JERICHO1.jpeg",
    second_image: "/images/committee/polog/JERICHO2.jpeg",
  },
  {
    name: "Jesslyn",
    full_name: "Jesslyn Mirable",
    year_course: "EEE/3",
    og: "OG 5",
    first_image: "/images/committee/polog/JESSLYN1.jpeg",
    second_image: "/images/committee/polog/JESSLYN2.jpeg",
  },
  {
    name: "Jonathan",
    full_name: "Jonathan William Kho",
    year_course: "CBE/2",
    og: "OG 6",
    first_image: "/images/committee/polog/JONATHAN1.jpeg",
    second_image: "/images/committee/polog/JONATHAN2.jpeg",
  },
  {
    name: "Jordan",
    full_name: "Jordan Audric Tanary",
    year_course: "MSE/2",
    og: "OG 8",
    first_image: "/images/committee/polog/JORDAN1.jpeg",
    second_image: "/images/committee/polog/JORDAN2.jpeg",
  },
  {
    name: "Marvel",
    full_name: "Marvel Christian Kusuma",
    year_course: "ME/2",
    og: "OG 1",
    first_image: "/images/committee/polog/MARVEL1.jpeg",
    second_image: "/images/committee/polog/MARVEL2.jpeg",
  },
  {
    name: "Matthew",
    full_name: "Matthew Anderson Kurniawan",
    year_course: "EEE/2",
    og: "OG 2",
    first_image: "/images/committee/polog/MATTHEW1.jpeg",
    second_image: "/images/committee/polog/MATTHEW2.jpeg",
  },
  {
    name: "Oro",
    full_name: "Nicholas Orotodan",
    year_course: "EEE/3",
    og: "OG 4",
    first_image: "/images/committee/polog/ORO1.jpeg",
    second_image: "/images/committee/polog/ORO2.jpeg",
  },
  {
    name: "Radja",
    full_name: "Hatta Radja Ismail",
    year_course: "ME/2",
    og: "OG 5",
    first_image: "/images/committee/polog/RADJA1.jpeg",
    second_image: "/images/committee/polog/RADJA2.jpeg",
  },
  {
    name: "Tano",
    full_name: "Jonatan Tano",
    year_course: "CEE/2",
    og: "OG 7",
    first_image: "/images/committee/polog/TANO1.jpeg",
    second_image: "/images/committee/polog/TANO2.jpeg",
  },
  {
    name: "Thomas",
    full_name: "Thomas Howen",
    year_course: "MAE/3",
    og: "OG 1",
    first_image: "/images/committee/polog/THOMAS1.jpeg",
    second_image: "/images/committee/polog/THOMAS2.jpeg",
  },
  {
    name: "Timothy",
    full_name: "Timothy Lani",
    year_course: "EEE/2",
    og: "OG 6",
    first_image: "/images/committee/polog/TIMOTHY1.jpeg",
    second_image: "/images/committee/polog/TIMOTHY2.jpeg",
  },
  {
    name: "Wilson",
    full_name: "Wilson Anjelo",
    year_course: "CBE/2",
    og: "OG 8",
    first_image: "/images/committee/polog/WILSON1.jpeg",
    second_image: "/images/committee/polog/WILSON2.jpeg",
  },
],
  },
  {
    title: "BFM",
    group_image: "/images/committee/bfm/BFM_MC.jpg",
    members: [
  {
    name: "Audria",
    full_name: "Audria Akbar",
    year_course: "MSE/1",
    og: "OG 1",
    first_image: "/images/committee/bfm/audria1.jpg",
    second_image: "/images/committee/bfm/audria2.jpg",
  },
  {
    name: "Christian",
    full_name: "Christian Vilaril Tjendra",
    year_course: "CBE/3",
    og: "OG 4",
    first_image: "/images/committee/bfm/christian1.jpg",
    second_image: "/images/committee/bfm/christian2.jpg",
  },
  {
    name: "Daniel",
    full_name: "Daniel Delin",
    year_course: "EEE/4",
    og: "OG 8",
    first_image: "/images/committee/bfm/daniel1.jpg",
    second_image: "/images/committee/bfm/daniel2.jpg",
  },
  {
    name: "Donni",
    full_name: "Donni Putera Sow",
    year_course: "PHY/4",
    og: "OG 4",
    first_image: "/images/committee/bfm/donni1.jpg",
    second_image: "/images/committee/bfm/donni2.jpg",
  },
  {
    name: "Ivonne",
    full_name: "Ivonne Wijaya",
    year_course: "CSC/2",
    og: "OG 5",
    first_image: "/images/committee/bfm/ivonne1.jpg",
    second_image: "/images/committee/bfm/ivonne2.jpg",
  },
  {
    name: "Keenan",
    full_name: "Keenan Jonathan",
    year_course: "CBE/4",
    og: "OG 4",
    first_image: "/images/committee/bfm/keenan1.jpg",
    second_image: "/images/committee/bfm/keenan2.jpg",
  },
  {
    name: "Melly",
    full_name: "Melly Wibowo",
    year_course: "ENE/3",
    og: "OG 7",
    first_image: "/images/committee/bfm/melly1.jpg",
    second_image: "/images/committee/bfm/melly2.jpg",
  },
  {
    name: "Michelle",
    full_name: "Michelle Hartanto",
    year_course: "BASA/2",
    og: "OG 2",
    first_image: "/images/committee/bfm/michelle1.jpg",
    second_image: "/images/committee/bfm/michelle2.jpg",
  },
  {
    name: "Nicholas",
    full_name: "Nicholas Elbert Liem",
    year_course: "CBE/4",
    og: "OG 6",
    first_image: "/images/committee/bfm/nicholas1.jpg",
    second_image: "/images/committee/bfm/nicholas2.jpg",
  },
  {
    name: "Owen",
    full_name: "Owen Nigel Tjiptarahardja",
    year_course: "BCG/4",
    og: "OG 7",
    first_image: "/images/committee/bfm/owen1.jpg",
    second_image: "/images/committee/bfm/owen2.jpg",
  },
  {
    name: "Stephanie",
    full_name: "Stephanie Nathania Subari",
    year_course: "ACDA/2",
    og: "OG 5",
    first_image: "/images/committee/bfm/stephanie1.jpg",
    second_image: "/images/committee/bfm/stephanie2.jpg",
  },
  {
    name: "Vincentius",
    full_name: "Vincentius Farrel Bhaskoro Setyanto",
    year_course: "EEE/2",
    og: "OG 3",
    first_image: "/images/committee/bfm/vicentius1.jpg",
    second_image: "/images/committee/bfm/vicentius2.jpg",
  },
  {
    name: "Viony",
    full_name: "Viony Prajogo",
    year_course: "IEM/3",
    og: "OG 1",
    first_image: "/images/committee/bfm/viony1.jpg",
    second_image: "/images/committee/bfm/viony2.jpg",
  },
],
  },
];